name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.2
  google_fonts: ^2.1.0
  dartz: ^0.10.0
  cached_network_image: ^3.1.0
  flutter_rating_bar: ^4.0.0
  about:
    path: ../about
  tv_series:
    path: ../tv_series
  movies:
    path: ../movies
  sqflite_sqlcipher: ^2.1.0
  encrypt: ^5.0.1
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.0


flutter:
