name: movies
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  about:
    path: ../about
  flutter_bloc: ^8.0.0
  equatable: ^2.0.2
  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.0

flutter:

